"""Mako template file for creating migration scripts.

Ref: http://alembic.zzzcomputing.com/en/latest/tutorial.html#creating-a-migration-script
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf6c9e8cf5fb'
down_revision = '91c123def456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###